# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_v2.proto

require 'google/protobuf'


descriptor_data = "\n\ruser_v2.proto\x12\x04user\"\x18\n\x05\x45mail\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"x\n\x04User\x12\x16\n\x0ewriter_version\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\n\n\x02id\x18\x05 \x01(\x05\x12\x1a\n\x05\x65mail\x18\x06 \x01(\x0b\x32\x0b.user.Email\x12\x0b\n\x03\x61ge\x18\x07 \x01(\x05\x42\nZ\x08/user-v2b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module User
  Email = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.Email").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.User").msgclass
end
